language: node_js

node_js:
  - "14"

env:
  - PORT=3333 HOST=http://localhost:3333 NODE_ENV=test ORIGIN=http://localhost:3333 JWT_SECRET=secrete-jwt-key JWT_EXPIRES_TIME=15d

script:
  - yarn lint
  - yarn test